<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <Description>Bambloo - WebSocket C# host for Discord communication on Windows</Description>
		<Version>1.0.0</Version>
		<Authors>Eli Soli</Authors>
    <PackageLicenseUrl>https://opensource.org/licenses/MIT</PackageLicenseUrl>

    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>

</Project>
